# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.14.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
'''This can be done in 2 ways.Firstly we can use the numpy size function and multiply the 
number of elements with the size of these elements(given by itemsize)

Secondly we can also do this by calling nbytes for a numpy array which basically does this job for us
'''
sample_arr=np.array([[0,0,0,0],[1,2,3,4],[2,3,4,5]])
print(sample_arr.shape)
# ?np.array
# np.size(sample_arr)*sample_arr.itemsize
sample_arr.nbytes

(3, 4)


96

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# help(np.add)
'''We can use the help function provided by python or use the numpy info function which loads the docstring
for any given function

For Interactive Prompts,both of these return the same output
'''
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
'''Simple Indexing same as python.'''
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
'''This Problem can also be done in multiple ways.We can use the arange function given by numpy to do so
or we can create a list comprehension in python and pass it to numpy \'s asarray function '''
dynamic_vector=np.arange(10,50)
other_vector=np.asarray([i for i in range(10,50)])
# print(dynamic_vector,dynamic_vector.shape)
print(other_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [14]:
'''For this,we can use the slicing reverse technique used in python'''
dynamic_vector=np.arange(10,50)[::-1]
print(dynamic_vector)
# ?np.arange

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
'''For this,we can use the reshape method given by numpy.Basically this method can convert the source
matrix/vector into a shape of our liking if it is possible.Else it gives us an error'''
thby3=np.array(np.arange(0,9)).reshape(3,3)
# ?np.array
print(thby3,thby3.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [18]:
'''We can do this by using the where function in numpy which gives the indexes based on a given condition 
or we can use the inbuilt function nonzero which can do the same job'''
non_zero=np.array([[1,2,0,0,4,0]])
print(np.where(non_zero !=0))
print(np.nonzero(non_zero))
# ??np.nonzero

(array([0, 0, 0]), array([0, 1, 4]))
(array([0, 0, 0]), array([0, 1, 4]))


#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
'''Using the ones function we can do this or we can create an array and then reshape it'''
idmatrix=np.ones((3,3))
print(idmatrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [37]:
'''This can be done in 2 ways.firstly the way that i chose was to create a random number ndarray using m*n*k numbers(27)
in this case,and then reshape it into a (m,n,k) matrix.Or we can do this as mentioned in the solutions by directly
passing the shape to numpy random classes random method'''

new_matrix=np.random.rand(27).reshape((3,3,3))

print(new_matrix)
print(np.random.random((3,3,3)))

[[[0.07809135 0.04898578 0.47558162]
  [0.9993894  0.02910353 0.71019356]
  [0.25686361 0.27938524 0.69425457]]

 [[0.6065161  0.10396111 0.52118283]
  [0.68819857 0.67293342 0.2669946 ]
  [0.37315374 0.44858262 0.5486767 ]]

 [[0.69513921 0.2035966  0.69175945]
  [0.76195683 0.22851447 0.15484736]
  [0.95394653 0.18001367 0.50401602]]]
[[[0.48372124 0.70822352 0.52408378]
  [0.26950103 0.43656129 0.93014059]
  [0.78892149 0.09945082 0.64039963]]

 [[0.06276586 0.00274591 0.90125876]
  [0.45546816 0.08854011 0.13264544]
  [0.35511955 0.27476579 0.88672656]]

 [[0.70766694 0.25992707 0.29547826]
  [0.35738838 0.61586472 0.61227287]
  [0.81622363 0.27039751 0.22491028]]]



#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [49]:
'''This can be done in 2 ways.firstly the way that i chose was to create a random number ndarray by directly
passing the shape to numpy random classes random method and passing the created array to the numpy min and max method.Or 
we can directly call the min and max on the created array itself.'''

new_matrix_10=np.random.random((10,10))
# print(new_matrix_10)
print(np.min(new_matrix_10),np.max(new_matrix_10))
print(new_matrix_10.min(),new_matrix_10.max())

0.024457449668070286 0.9990899170408306
0.024457449668070286 0.9990899170408306


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [55]:
'''We can do this by calling the mean method on our created numpy array created using the random.random method'''
new_array_30=np.random.random(30)
print(new_array_30.mean())

0.4872822640639497


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [90]:
'''We can do this via simple indexing logic.For any given matrix of size m X n or m X m or n X n.We need to fill zeroes
in rows from the first row and column(Because the border will cover the first row,first column and last row last column) 
so this should run from the first row and first column to the last row -1 and last column -1'''

m,n=10,10
arrayzeroes=np.ones((m,n))
arrayzeroes[1:m-1,1:n-1]=0
print(arrayzeroes)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
'''We can do this using the numpy pad function.For this,we can also use methods like insert,vstack and hstack.'''
m,n=4,5

outer_border_matrix=np.ones((m,n))
print(outer_border_matrix)
np.pad(outer_border_matrix,(1),'constant')

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [40]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3==3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [14]:
'''This can be done by using the np.diag method(Just found this function) or 
we can manually use the indices of the elements to do so.Although this will not work for any other matrix,for
this question this is ok'''

fivex5matrix=np.arange(25).reshape(5,5)
# print(fivex5matrix)
fivex5matrix[1,0]=1
fivex5matrix[2,1]=2
fivex5matrix[3,2]=3
fivex5matrix[4,3]=4
print(fivex5matrix)

[[ 0  1  2  3  4]
 [ 1  6  7  8  9]
 [10  2 12 13 14]
 [15 16  3 18 19]
 [20 21 22  4 24]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [45]:
'''Hackey Method.Create a 8x8 matrix and then unroll it into one big vector using ravel.Then turn 
every alternate value into a zero or one(as needed) and then call the reshape command'''
checkmatrix=np.ones((8,8)).ravel()
checkmatrix[0::2]=0
checkmatrix.reshape((8,8))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [55]:
'''This function basically returns us the index at whihc the elment is to be found.We can also pass a list of
indices to search upon also'''

newarray=np.random.random((6,7,8))
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [61]:
'''The tile function basically repeats a given array n number of times.So for this we can repeat our single row 
8 no of times and the column should be just given a single value(1) so that the values are repeated along the 
columnaxis just once.'''

newarray=np.array([0,1,0,1,0,1,0,1])
np.tile(newarray,((8,1)))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [76]:
'''To normalize a matrix,means to divide the individual elements of a matrix by the determinant of the matrix.
The determinant is a special value unique to a matrix.This can be calculated by taking the minors along each 
row of the matrix.Refer to this link https://en.wikipedia.org/wiki/Determinant'''

normalizematrinx=np.random.random((5,5))
determinant=np.linalg.det(normalizematrinx)
normalizematrinx/=determinant

print(normalizematrinx)

[[0.51099193 0.66140224 0.44830203 0.19321164 0.65814295]
 [0.20223691 0.34620438 0.02645046 0.78087928 0.37897902]
 [0.63919224 0.23977047 0.06149836 0.36376474 0.63215891]
 [0.0155844  0.40818607 0.71835942 0.61074759 0.8811245 ]
 [0.09774466 0.01534684 0.15358355 0.9697329  0.47281814]]
0.028139673339381156
[[18.15912801 23.50426161 15.93131621  6.86616488 23.38843613]
 [ 7.18689602 12.30307047  0.93997038 27.75011902 13.46778328]
 [22.71498447  8.52072694  2.185468   12.92711317 22.46504075]
 [ 0.55382317 14.50571459 25.5283498  21.70414651 31.31253468]
 [ 3.47355349  0.54538102  5.45790103 34.46141275 16.80254543]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [44]:
'''We can do this by 2 methods.Firstly we can use the dot method on a given matrix and multiply it with the second matrix
as shown.Or we can use the @ operator(overloaded operator) to perform the same operation.This syntax is becoming
increasingly common so its good to use this syntax.'''

n5X3=np.random.random((5,3))
n3x2=np.random.random((3,2))

print(n5X3 @ n3x2)
print(n5X3.dot(n3x2))

[[0.95661141 0.64514016]
 [0.66807619 0.31910586]
 [0.57827602 0.24663639]
 [0.68355174 0.3410374 ]
 [0.61122    0.33484139]]
[[0.95661141 0.64514016]
 [0.66807619 0.31910586]
 [0.57827602 0.24663639]
 [0.68355174 0.3410374 ]
 [0.61122    0.33484139]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [110]:
'''Negation in numpy means that we simply return the multiplication of the value with a single -1.Was trying to solve
this usin numpy functions when i realised i did not need those functions.'''

onedarray=np.arange(100)[::-1]
onedarray[(onedarray>3) & (onedarray<=8)] *=-1
onedarray

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9, -8, -7, -6, -5, -4,  3,  2,  1,  0])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [121]:
'''The second arg to sum reffers to the starting index from which the summation should take place.
But for the np.sum function,the second arg reffers to the axis along which the sum is to be performed and in this case,
the axis -1 reffers to a sum along the row hence we get the sum as 10'''
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [132]:
intvector=np.array(range(5))
intvector**intvector
intvector/1/1
intvector < -intvector
intvector<intvector>intvector
2<<intvector>>2

'''THe only expression in this set which is illegal is the 6th expression as we cannot compute less than or greater
than operations for an entire array.These operations need to be performed element wise which can be done using & or |
operators(and operator or operator)'''

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [133]:
np.array(0) / np.array(0)

nan

In [134]:
np.array(0) // np.array(0)

0

In [135]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [139]:
# np.lookfor("common")
# ?np.intersect1d

'''The intersect1d function accepts 2 arrays as parameters and then returns the common elements in both those arrays'''

firstarray=np.arange(100)
secondarray=np.arange(200)

common=np.intersect1d(firstarray,secondarray)
common

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [140]:
'''The following expression is not true as both these numbers are negative,the sqrt for negative no is not defined
for np.sqrt function but is defined for the np.emath.sqrt function.'''
# ?np.emath.sqrt
# ?np.sqrt

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [151]:
# np.lookfor("today")
np.array(['2019-03-31','2019-04-01','2019-04-02'],dtype=datetime64)

array(['2019-03-31', '2019-04-01', '2019-04-02'], dtype='datetime64[D]')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [153]:
'''The dtype datetime64 can be used to render the dates for a particular month by providing the np.arange mehtod
with the starting and ending dates using which it renders the dates within the given time period'''

np.arange('2016-07-01','2016-08-01',dtype=datetime64)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [20]:
'''We can generate an initial matrix using zeros or random module.Then for each row,we can replace it with the 
arange list values.Or we can append a single list of values ranging from 0,4'''

init_matrix=np.zeros((5,5))
init_matrix+=np.arange(5)
print(init_matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [16]:
'''The np.from iter function allows us to generate an array from  a generator expression'''

generator_exp=(i for i in range(11))
print(np.fromiter(generator_exp,dtype=int))

<generator object <genexpr> at 0x7f04bca88f10>
[ 0  1  2  3  4  5  6  7  8  9 10]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [162]:
'''Using the np.linspace function we can create random numbers within a given interval range.It has an argument 
endpoint which specifies whetehr to include the last elment or not.Zero is by default included so we can just
start our indexing process from the next element after zero'''

np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [164]:
'''Create a random matrix using any method and just use the sort method like this or directly on the array.'''
np.sort(np.linspace(0,1,10))

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.matrix.sum
    Returns the sum of the matrix elements, along the given axis.
numpy.logaddexp2
    Logarit

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [41]:
'''The np.equal method gives us the element truthwise comparision whereas the np.allclose function gives us the
result if all the elements are equal or not.

Allclose works it both the matrixes are of the same dimensions(shape) while array equal first compares the shape 
and then checks the elements.So the array_equal method is better
'''

randarray1=np.random.rand(4)
randarray2=np.random.rand(5)

# print(np.allclose(randarray1,randarray2))
print(np.array_equal(randarray1,randarray2))

# np.lookfor('equal')
# ?np.array_equal

False


#### 43. Make an array immutable (read-only) (★★☆)

In [56]:
'''The Simplest Method would be to convert the array into a tuple(immutable object)

The other way simple way is to set a writable flag for an array(refer to the above answer)

https://stackoverflow.com/questions/5541324/immutable-numpy-array

'''
init_array=np.random.rand(10)
init_array.setflags(write=False)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [66]:
'''Using argmax,we can find the index of the maximum element in the array and then directly assign that index to 
zero'''

init_array=np.random.rand(10)
maxval=np.argmax(init_array)

# index_max=np.where(maxval,init_array)
init_array[maxval]=0

print(init_array)

[0.         0.47079336 0.51235952 0.26298048 0.09889671 0.79884636
 0.14280278 0.80566579 0.8795261  0.49992016]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [75]:
'''Get the mean along the row(axis=1) and create it inot a new array and subtract from the original array'''
init_array=np.random.rand(9).reshape(3,3)

mean=np.mean(init_array,axis=1)

print(init_array)
print(init_array-mean)

[[0.15526401 0.36099196 0.95507526]
 [0.13015837 0.27284659 0.80911787]
 [0.96565706 0.09242216 0.58342427]]
[[-0.33517973 -0.04304898  0.40790743]
 [-0.36028537 -0.13119436  0.26195004]
 [ 0.47521332 -0.31161878  0.03625644]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)